### ISSUE TITLE
New dropdown genotype feature in the Map view

### ISSUE THREAD

**Issue by lcerdeira** [typhoidgenomics/TyphiNET#43]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lcerdeira** [comment]
@vLSHTM did you manage to implement this feature?

**Comment by vLSHTM** [comment]
@lcerdeira If this is a question about "Genotype Prevalence Dropdown", then It is Implemented for AMRnet only.

**Comment by lcerdeira** [comment]
Implemented by branch van/genotypep
